# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eb571f67198c1ee9ea5a6a1b3fbd1367d91528daa95f5bb21fb7f58133d79b961f41350cbd2078a68760c94f383fee38a04bac4a4266080cd0e6285566471a98

test:
  secret_key_base: 89754970a469d0a6935d30e5d42d7fb16ff4d4ce60503f066bb302a02805f02d86492d952e9223db5825b2955d034b0003864aed80afab582dd10a8a378b23a5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
